# 🚀 ML Preprocessing Assignment  

## 📌 Objective  
**To apply categorical encoding and feature scaling techniques on a passenger dataset.**

# Dataset

In [21]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, RobustScaler

# Creating dataset
data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'City': ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi'],
    'Size': ['Small', 'Large', 'Medium', 'Large', 'Small'],
    'Age': [25, 45, 32, 60, 28],
    'Fare': [15, 300, 85, 450, 20]
}

df = pd.DataFrame(data)
df

   Gender     City    Size  Age  Fare
0    Male   Mumbai   Small   25    15
1  Female    Delhi   Large   45   300
2  Female  Chennai  Medium   32    85
3    Male   Mumbai   Large   60   450
4  Female    Delhi   Small   28    20

## Task 1: Categorical Encoding  

- Gender → Label Encoding  
- City → One-Hot Encoding (drop first column)  
- Size → Ordered Encoding

In [22]:
# Gender → Label Encoding]
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

# City → One-Hot Encoding
df = pd.get_dummies(df, columns=['City'], drop_first=True, dtype = int)

# Size → Ordered Encoding
size_mapping = {'Small': 0, 'Medium': 1, 'Large': 2}
df['Size'] = df['Size'].map(size_mapping)

df

   Gender  Size  Age  Fare  City_Delhi  City_Mumbai
0       1     0   25    15           0            1
1       0     2   45   300           1            0
2       0     1   32    85           0            0
3       1     2   60   450           0            1
4       0     0   28    20           1            0

## Task 2: Feature Scaling  

**Applying RobustScaler due to presence of outlier in Fare column.**

In [23]:
scaler = RobustScaler()

df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

# RobustScaler is used because Fare contains an outlier (450),
# IUt scales data using median and IQR, making it robust to outliers.

df

   Gender  Size       Age      Fare  City_Delhi  City_Mumbai
0       1     0 -0.411765 -0.250000           0            1
1       0     2  0.764706  0.767857           1            0
2       0     1  0.000000  0.000000           0            0
3       1     2  1.647059  1.303571           0            1
4       0     0 -0.235294 -0.232143           1            0

## ✅ Conclusion  

**Successfully applied encoding and scaling techniques to prepare the dataset for machine learning.**